#!/usr/bin/env bash
#
# Deploys the Team 10 site on Ubuntu 24.04. Safe to re-run: it provisions on the
# first run and updates to the latest master on every run after that.
#
# Usage, on the EC2 instance:
#   curl -fsSL https://raw.githubusercontent.com/MenPeko/CSC648-S01-FA26-10-Repository/master/application/deploy/bootstrap.sh | sudo bash
#
# Or, if the repository is already cloned:
#   sudo bash application/deploy/bootstrap.sh

set -euo pipefail

REPO_URL="https://github.com/MenPeko/CSC648-S01-FA26-10-Repository.git"
REPO_DIR="/srv/CSC648-S01-FA26-10-Repository"
BRANCH="${BRANCH:-master}"
APP_DIR="$REPO_DIR/application"
SERVICE="team10"

step() { printf '\n\033[1;34m==> %s\033[0m\n' "$1"; }
warn() { printf '\033[1;33mWARNING: %s\033[0m\n' "$1"; }

if [[ $EUID -ne 0 ]]; then
    echo "Run this with sudo: sudo bash $0" >&2
    exit 1
fi

step "Installing system packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq git nginx python3.12 python3.12-venv curl

step "Fetching the application source ($BRANCH)"
# Allow root to operate on the checkout even if a teammate cloned it as ubuntu.
if ! git config --global --get-all safe.directory 2>/dev/null | grep -qx "$REPO_DIR"; then
    git config --global --add safe.directory "$REPO_DIR"
fi
if [[ -d "$REPO_DIR/.git" ]]; then
    git -C "$REPO_DIR" fetch --quiet origin "$BRANCH"
    # Discard server-side edits so the deployment always matches master.
    # Ignored files such as .env are left untouched.
    git -C "$REPO_DIR" reset --hard --quiet "origin/$BRANCH"
else
    git clone --quiet --branch "$BRANCH" "$REPO_URL" "$REPO_DIR"
fi
echo "Now at: $(git -C "$REPO_DIR" log --oneline -1)"

step "Building the virtual environment"
if [[ ! -x "$APP_DIR/venv/bin/python" ]]; then
    python3.12 -m venv "$APP_DIR/venv"
fi
"$APP_DIR/venv/bin/pip" install --quiet --upgrade pip
"$APP_DIR/venv/bin/pip" install --quiet -r "$APP_DIR/requirements.txt"
echo "Python: $("$APP_DIR/venv/bin/python" --version)"

step "Configuring secrets"
if [[ -f "$REPO_DIR/.env" ]]; then
    echo "Keeping the existing .env"
else
    secret="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
    cat > "$REPO_DIR/.env" <<EOF
# Generated by deploy/bootstrap.sh. Never commit this file.
SECRET_KEY=$secret
FLASK_ENV=production

# Fill these in when the database is wired up (not needed for Milestone 0).
DB_HOST=localhost
DB_PORT=3306
DB_NAME=csc648_team10
DB_USER=
DB_PASSWORD=
EOF
    echo "Created $REPO_DIR/.env with a freshly generated SECRET_KEY"
fi
# Readable by the Gunicorn user only, never world-readable.
chown root:www-data "$REPO_DIR/.env"
chmod 640 "$REPO_DIR/.env"

step "Installing the Gunicorn service"
install -m 644 "$APP_DIR/deploy/$SERVICE.service" "/etc/systemd/system/$SERVICE.service"
systemctl daemon-reload
systemctl enable --quiet "$SERVICE"
systemctl restart "$SERVICE"

step "Installing the Nginx site"
install -m 644 "$APP_DIR/deploy/nginx-team10.conf" "/etc/nginx/sites-available/$SERVICE"
ln -sfn "/etc/nginx/sites-available/$SERVICE" "/etc/nginx/sites-enabled/$SERVICE"
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl reload nginx

step "Opening the host firewall"
if command -v ufw >/dev/null && ufw status | grep -q "Status: active"; then
    ufw allow "Nginx Full" >/dev/null
    echo "ufw is active; allowed HTTP and HTTPS"
else
    echo "ufw is inactive; nothing to open on the host"
fi

step "Verifying"
sleep 2
gunicorn_code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 http://127.0.0.1:8000/ || true)"
nginx_code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 http://127.0.0.1/ || true)"
echo "Gunicorn on 127.0.0.1:8000 -> $gunicorn_code"
echo "Nginx on 127.0.0.1:80     -> $nginx_code"

if [[ "$nginx_code" != "200" ]]; then
    warn "The site did not return 200 locally. Useful commands:"
    echo "  systemctl status $SERVICE --no-pager"
    echo "  journalctl -u $SERVICE -n 50 --no-pager"
    echo "  tail -n 50 /var/log/nginx/team10.error.log"
    exit 1
fi

printf '\n\033[1;32mDeployed.\033[0m Public URL: http://ec2-13-52-242-59.us-west-1.compute.amazonaws.com\n'
echo "If that URL times out from your laptop, the AWS security group is still"
echo "blocking inbound TCP 80; the site itself is serving correctly here."
